# Generated by Django 4.2.5 on 2024-01-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ad_salary',
        ),
        migrations.DeleteModel(
            name='adminemploy',
        ),
        migrations.DeleteModel(
            name='adminnav',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='data',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='emp',
        ),
        migrations.RemoveField(
            model_name='emplo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='emplo',
            name='location',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='employnav',
        ),
        migrations.DeleteModel(
            name='ESIC',
        ),
        migrations.DeleteModel(
            name='info',
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='otp',
        ),
        migrations.DeleteModel(
            name='P_tax',
        ),
        migrations.DeleteModel(
            name='PF',
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='role',
        ),
        migrations.DeleteModel(
            name='TDS',
        ),
        migrations.DeleteModel(
            name='ts',
        ),
        migrations.DeleteModel(
            name='typeofd',
        ),
        migrations.DeleteModel(
            name='types',
        ),
        migrations.DeleteModel(
            name='data',
        ),
        migrations.DeleteModel(
            name='depart',
        ),
        migrations.DeleteModel(
            name='Emplo',
        ),
        migrations.DeleteModel(
            name='loca',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
        migrations.DeleteModel(
            name='Reimbursement',
        ),
    ]
