# Generated by Django 4.2.5 on 2024-01-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_delete_ad_salary_delete_adminemploy_delete_adminnav_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationname', models.CharField(max_length=100)),
                ('registrationno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='images/')),
                ('phoneno', models.BigIntegerField()),
                ('strength', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('confirm_password', models.CharField(default='', max_length=100)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationname', models.CharField(max_length=100)),
                ('registrationno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='images/')),
                ('phoneno', models.BigIntegerField()),
                ('strength', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('confirm_password', models.CharField(default='', max_length=100)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(db_index=True, max_length=200)),
                ('nav_url', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning.homenav')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
