# Generated by Django 5.0.1 on 2024-01-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_schools_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
