# Generated by Django 5.0.1 on 2024-01-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
    ]
