# Generated by Django 5.0.1 on 2024-01-04 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_menuitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning.menuitem'),
        ),
    ]
