# Generated by Django 5.0.1 on 2024-01-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dashboard',
        ),
    ]
