# Generated by Django 5.0.1 on 2024-01-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
