# Generated by Django 5.0.1 on 2024-01-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_student_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
