# Generated by Django 5.0.1 on 2024-01-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_alter_customuser_email_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Studentstable',
        ),
        migrations.AlterModelTable(
            name='studentstable',
            table='Studentstable',
        ),
    ]
