# Generated by Django 5.0.1 on 2024-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_rename_student_studentstable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='xyz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'xyz',
            },
        ),
    ]
