# Generated by Django 5.0.1 on 2024-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_student_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'lms',
            },
        ),
    ]
