# Generated by Django 5.0.1 on 2024-01-10 11:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_lms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='strength',
            new_name='course1',
        ),
        migrations.AddField(
            model_name='teachers',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 11, 13, 55, 649847)),
        ),
        migrations.AddField(
            model_name='teachers',
            name='experiance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phoneno',
            field=models.CharField(default='', max_length=100),
        ),
    ]
