# Generated by Django 5.0.1 on 2024-01-10 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_course_subject_rename_strength_teachers_course1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 11, 27, 49, 329627)),
        ),
    ]
