# Generated by Django 5.0.1 on 2024-01-10 12:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_alter_teachers_dob_teachersidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 12, 46, 25, 769911)),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subjectname', models.CharField(default='', max_length=100)),
                ('chapter_no', models.CharField(default='', max_length=100)),
                ('urls', models.CharField(default='', max_length=100)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdrop', to='learning.uploadedfile')),
            ],
        ),
    ]
