# Generated by Django 5.0.1 on 2024-01-10 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_alter_teachers_dob_admindrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('subject1', models.TextField()),
                ('subject2', models.TextField()),
                ('subject3', models.TextField()),
                ('subject4', models.TextField()),
                ('subject5', models.TextField()),
                ('subject6', models.TextField()),
                ('subject7', models.TextField()),
                ('subject8', models.TextField()),
                ('subject9', models.TextField()),
                ('subject10', models.TextField()),
                ('subject11', models.TextField()),
                ('subject12', models.TextField()),
                ('subject13', models.TextField()),
                ('subject14', models.TextField()),
                ('subject15', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 15, 17, 39, 923019)),
        ),
    ]
