# Generated by Django 5.0.1 on 2024-01-11 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_topics_alter_teachers_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='topics',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 9, 13, 6, 458867)),
        ),
    ]
