# Generated by Django 5.0.1 on 2024-01-11 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_topics_alter_teachers_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='topics',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 10, 42, 13, 242312)),
        ),
    ]
