# Generated by Django 5.0.1 on 2024-01-11 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_alter_teachers_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 12, 1, 2, 789728)),
        ),
        migrations.AlterModelTable(
            name='homenav',
            table='learning_homenav',
        ),
    ]
