# Generated by Django 5.0.1 on 2024-01-18 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0041_topics_alter_teachers_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='stdclass1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subid', models.IntegerField()),
                ('chaptername', models.CharField(max_length=100)),
                ('chapterdis', models.TextField(default=None)),
                ('pdf', models.FileField(default=None, upload_to='pdf_files/')),
                ('classes', models.CharField(default=None, max_length=100)),
                ('classid', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 18, 14, 45, 31, 230240)),
        ),
    ]
