# Generated by Django 5.0.1 on 2024-01-24 18:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0054_alter_teachers_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 18, 30, 40, 133993)),
        ),
        migrations.CreateModel(
            name='studentnav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(db_index=True, max_length=200)),
                ('nav_url', models.CharField(max_length=100)),
                ('icon', models.CharField(default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning.studentnav')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
