# Generated by Django 4.2.7 on 2024-02-01 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0055_alter_teachers_dob_studentnav'),
    ]

    operations = [
        migrations.CreateModel(
            name='applogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 17, 20, 16, 709616)),
        ),
    ]
