# Generated by Django 4.2.3 on 2024-02-02 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0058_examcards_examcarl_examcont_alter_teachers_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stdclass',
            old_name='subject_description',
            new_name='classid',
        ),
        migrations.RemoveField(
            model_name='stdclass',
            name='subjecttitle',
        ),
        migrations.AddField(
            model_name='stdclass',
            name='classes',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='stdclass',
            name='pdf',
            field=models.FileField(default=None, upload_to='pdf_files/'),
        ),
        migrations.AlterField(
            model_name='stdclass',
            name='subid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 56, 33, 520699)),
        ),
    ]
