# Generated by Django 4.2.3 on 2024-02-02 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0063_delete_stdclass_alter_teachers_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='stdclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subid', models.CharField(max_length=200)),
                ('chaptername', models.CharField(max_length=100)),
                ('chapterdis', models.TextField(default=None)),
                ('pdf', models.FileField(default=None, upload_to='pdf_files/')),
                ('classes', models.CharField(default=None, max_length=100)),
                ('classid', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 14, 12, 14, 99495)),
        ),
    ]
