# Generated by Django 5.0.1 on 2024-02-05 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0082_cardfee_crfee_fee_alter_teachers_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='staff_fea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph2', models.CharField(max_length=600)),
                ('discription', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='staff_imp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('paragraph1', models.CharField(max_length=400)),
                ('paragraph2', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='staff_prob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 11, 39, 16, 274956)),
        ),
    ]
