# Generated by Django 5.0.1 on 2024-02-05 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0083_staff_staff_fea_staff_imp_staff_prob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 12, 36, 19, 649370)),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
