# Generated by Django 5.0.1 on 2024-02-05 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0084_alter_teachers_dob_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendmanagecards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image3', models.ImageField(upload_to='images/')),
                ('field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='attendmanagecarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='attendmanagecontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('heading', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 16, 12, 47, 266853)),
        ),
    ]
