# Generated by Django 5.0.1 on 2024-02-06 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0088_contactinfo_contactinfo2_contactmessage_footerlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='liveclasscards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image3', models.ImageField(upload_to='images/')),
                ('field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='liveclasscarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='liveclasscontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('heading', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 12, 14, 0, 461898)),
        ),
    ]
