# Generated by Django 5.0.1 on 2024-02-07 14:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0092_student_mystudent_student_username_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='different_shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 14, 21, 6, 965841)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 14, 21, 6, 937216)),
        ),
        migrations.CreateModel(
            name='compose_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageType', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('studentname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
                ('teachername', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.teachers')),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='shift_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.different_shifts'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Teacher_Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_off', models.CharField(max_length=100)),
                ('in_time', models.TimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 21, 6, 940661))),
                ('late_mark_time', models.TimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 21, 6, 940661))),
                ('out_time', models.TimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 21, 6, 940661))),
                ('half_daytime', models.TimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 21, 6, 940661))),
                ('facult_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.teachers')),
                ('shift_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.different_shifts')),
            ],
        ),
    ]
