# Generated by Django 5.0.1 on 2024-02-07 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0094_alter_leave_today_alter_teacher_shifts_half_daytime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='shift_name',
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 14, 24, 3, 276857)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 14, 24, 3, 256619)),
        ),
        migrations.DeleteModel(
            name='Teacher_Shifts',
        ),
    ]
