# Generated by Django 5.0.1 on 2024-02-07 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0098_alter_leave_today_alter_teacher_shifts_half_daytime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_shifts',
            name='facult_name',
        ),
        migrations.RemoveField(
            model_name='teacher_shifts',
            name='shift_name',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='shift_name',
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 14, 28, 53, 446371)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 14, 28, 53, 420443)),
        ),
        migrations.DeleteModel(
            name='compose_message',
        ),
        migrations.DeleteModel(
            name='Teacher_Shifts',
        ),
    ]
