# Generated by Django 5.0.1 on 2024-02-07 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0101_alter_leave_today_alter_teachers_dob_compose_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 14, 30, 50, 31252)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 14, 30, 50, 10308)),
        ),
        migrations.DeleteModel(
            name='compose_message',
        ),
    ]
