# Generated by Django 5.0.1 on 2024-02-07 14:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0105_alter_leave_today_alter_teachers_dob_teacher_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='shift_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='learning.different_shifts'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 14, 35, 48, 897796)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 35, 48, 876888)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 35, 48, 876888)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 35, 48, 876888)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 35, 48, 876888)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 14, 35, 48, 875893)),
        ),
    ]
