# Generated by Django 5.0.1 on 2024-02-19 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0127_admin_main_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='content_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('content1', models.TextField()),
                ('image1', models.ImageField(default=None, upload_to='media/')),
                ('title2', models.CharField(default=None, max_length=100)),
                ('content2', models.TextField(default=None)),
                ('image2', models.ImageField(default=None, upload_to='media/')),
                ('title3', models.CharField(default=None, max_length=100)),
                ('content3', models.TextField(default=None)),
                ('image3', models.ImageField(default=None, upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 13, 44, 1, 799225)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 19, 13, 44, 1, 779275)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 19, 13, 44, 1, 778281)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 19, 13, 44, 1, 778281)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 19, 13, 44, 1, 779275)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 19, 13, 44, 1, 777280)),
        ),
    ]
