# Generated by Django 5.0.1 on 2024-02-20 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0128_carditems_carousel_img_content_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='content2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fee',
            name='content3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fee',
            name='photo2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fee',
            name='photo3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fee',
            name='title2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fee',
            name='title3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 9, 52, 4, 953745)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 20, 9, 52, 4, 934797)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 20, 9, 52, 4, 934797)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 20, 9, 52, 4, 934797)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 20, 9, 52, 4, 934797)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 20, 9, 52, 4, 933760)),
        ),
    ]
