# Generated by Django 5.0.1 on 2024-02-20 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0130_card_cimage_library_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendmanagecontent',
            name='content1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='attendmanagecontent',
            name='heading1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='attendmanagecontent',
            name='image2',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 13, 56, 23, 445786)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 20, 13, 56, 23, 426690)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 20, 13, 56, 23, 426690)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 20, 13, 56, 23, 426690)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 20, 13, 56, 23, 426690)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 20, 13, 56, 23, 425693)),
        ),
    ]
