# Generated by Django 5.0.1 on 2024-02-22 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0139_liveclasscontent_content1_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablecont',
            name='content1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='timetablecont',
            name='photo1',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='timetablecont',
            name='title1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 13, 45, 35, 661612)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 22, 13, 45, 35, 641541)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 22, 13, 45, 35, 641541)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 22, 13, 45, 35, 641541)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 22, 13, 45, 35, 641541)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 22, 13, 45, 35, 640504)),
        ),
    ]
