# Generated by Django 5.0.1 on 2024-03-01 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0144_leave_schoolid_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose_message',
            name='is_status',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='compose_message',
            name='read1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 9, 28, 22, 950936)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 1, 9, 28, 22, 935315)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 1, 9, 28, 22, 935315)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 1, 9, 28, 22, 935315)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 1, 9, 28, 22, 935315)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 3, 1, 9, 28, 22, 935315)),
        ),
    ]
