# Generated by Django 5.0.1 on 2024-03-18 14:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0158_text_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 14, 17, 28, 31713)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 18, 14, 17, 28, 10654)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 18, 14, 17, 28, 10654)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 18, 14, 17, 28, 10654)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 18, 14, 17, 28, 10654)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 14, 17, 28, 9657)),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('time', models.TimeField(default=datetime.time(14, 17, 28, 52268))),
                ('google_meet_link', models.URLField(blank=True, max_length=500, null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.cls_name')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.schools')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.teachers')),
            ],
        ),
    ]
