# Generated by Django 5.0.1 on 2024-03-19 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0160_oauthcredentials_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='google_meet_link',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='message',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='school',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(default=datetime.time(9, 53, 50, 941709)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meet_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting', max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 53, 50, 923047)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 19, 9, 53, 50, 864064)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 19, 9, 53, 50, 864064)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 19, 9, 53, 50, 864064)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 19, 9, 53, 50, 864064)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 9, 53, 50, 860581)),
        ),
    ]
