# Generated by Django 5.0.1 on 2024-03-19 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0161_remove_meeting_class_level_remove_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 10, 6, 17, 200241)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(default=datetime.time(10, 6, 17, 211773)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 19, 10, 6, 17, 155845)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 19, 10, 6, 17, 155845)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 19, 10, 6, 17, 155845)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 19, 10, 6, 17, 155845)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 10, 6, 17, 154191)),
        ),
    ]
