# Generated by Django 5.0.1 on 2024-03-20 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0176_zoommeeting_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 8, 45, 663246)),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='choice1',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='choice2',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='choice3',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='choice4',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='is_correct',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='question',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 20, 11, 8, 45, 623434)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 20, 11, 8, 45, 623434)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 20, 11, 8, 45, 623434)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 20, 11, 8, 45, 623434)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 11, 8, 45, 622445)),
        ),
    ]
