# Generated by Django 4.2.4 on 2024-04-12 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0187_pricingplan_alter_leave_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_image',
            name='content4',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='content_image',
            name='image4',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='content_image',
            name='title4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 10, 36, 521964)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 4, 12, 14, 10, 36, 504015)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 4, 12, 14, 10, 36, 504015)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 4, 12, 14, 10, 36, 504015)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 4, 12, 14, 10, 36, 504015)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 4, 12, 14, 10, 36, 503014)),
        ),
    ]
