# Generated by Django 4.2.4 on 2024-04-24 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0205_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 9, 19, 23, 662758)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 9, 19, 23, 690683)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 24, 9, 19, 23, 657771)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 24, 9, 19, 23, 657771)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 4, 24, 9, 19, 23, 668781)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 4, 24, 9, 19, 23, 668781)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 4, 24, 9, 19, 23, 668781)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 4, 24, 9, 19, 23, 668781)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 4, 24, 9, 19, 23, 667763)),
        ),
    ]
