# Generated by Django 4.1.3 on 2024-06-26 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0218_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upi', models.CharField(max_length=100)),
                ('DebitCreat', models.BigIntegerField()),
                ('UpiID', models.BigIntegerField()),
                ('cardnumber', models.BinaryField()),
                ('expiry', models.DateField()),
                ('cvc', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='fee_payment',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='fee_payment',
            name='transaction_datetime',
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 14, 38, 41, 696971)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 14, 38, 41, 726890)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 26, 14, 38, 41, 693940)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 26, 14, 38, 41, 693940)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 6, 26, 14, 38, 41, 703916)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 6, 26, 14, 38, 41, 703916)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 6, 26, 14, 38, 41, 703916)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 6, 26, 14, 38, 41, 703916)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 14, 38, 41, 702920)),
        ),
    ]
