# Generated by Django 4.1.3 on 2024-07-10 06:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0232_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='event_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 11, 57, 3, 153100)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 11, 57, 3, 191901)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 10, 11, 57, 3, 152065)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 10, 11, 57, 3, 152065)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 7, 10, 11, 57, 3, 160507)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 7, 10, 11, 57, 3, 160507)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 7, 10, 11, 57, 3, 160507)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 7, 10, 11, 57, 3, 160507)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 7, 10, 11, 57, 3, 160507)),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='meeting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
