# Generated by Django 4.1.3 on 2024-08-22 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0249_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='password',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='days_monthly',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='days_yearly',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='schools',
            name='plan_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 12, 45, 1, 371004)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 12, 45, 1, 439821)),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schools',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='schools',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 22, 12, 45, 1, 366016)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 22, 12, 45, 1, 366016)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 22, 12, 45, 1, 389952)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 22, 12, 45, 1, 388954)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 22, 12, 45, 1, 388954)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 22, 12, 45, 1, 388954)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 12, 45, 1, 382971)),
        ),
        migrations.AlterModelTable(
            name='schools',
            table='Schools',
        ),
    ]
